# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testerName', models.CharField(default='AutoTester', max_length=200)),
                ('testerVersion', models.CharField(default='v1.0', max_length=40)),
                ('lensType', models.CharField(default='piCam-FE', max_length=40)),
                ('fisheyeExpansionFactor', models.FloatField(default=1.2)),
                ('cameraWidthLowRes', models.IntegerField(default=480)),
                ('cameraHeightLowRes', models.IntegerField(default=640)),
            ],
        ),
    ]
