# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TesterExternal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testerName', models.CharField(default='AutoTester', max_length=200)),
                ('testerVersion', models.CharField(default='v1.0', max_length=40)),
                ('lensType', models.CharField(default='piCam-FE', max_length=40)),
                ('fisheyeExpansionFactor', models.FloatField(default=1.2)),
                ('cameraWidthLowRes', models.IntegerField(default=480)),
                ('cameraHeightLowRes', models.IntegerField(default=640)),
                ('tooDarkThreshold', models.IntegerField(default=30)),
                ('videoStreamingPort', models.IntegerField(default=8080)),
                ('pumpPurgeTimeSeconds', models.IntegerField(default=4)),
                ('mixerCleanTimeSeconds', models.IntegerField(default=4)),
                ('mixerCleanCycles', models.IntegerField(default=2)),
                ('fillTimeForPerML', models.FloatField(default=1)),
                ('reagentRemainingMLAlarmThreshold', models.FloatField(default=1.0)),
                ('reagentAlmostEmptyAlarmEnable', models.BooleanField(default=True)),
                ('pauseInSecsBeforeEmptyingMixingChamber', models.IntegerField(default=10)),
                ('iftttSecretKey', models.CharField(default=None, max_length=50)),
                ('sendMeasurementReports', models.BooleanField(default=False)),
                ('enableConsoleOutput', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Tester',
        ),
    ]
