# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0002_auto_20170818_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResultsExternal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testPerformed', models.CharField(default=None, max_length=200)),
                ('testResults', models.FloatField(default=None)),
                ('datePerformed', models.DateTimeField(verbose_name='dateTested')),
            ],
        ),
    ]
