# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 04:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0003_testresultsexternal'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorSheetExternal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colorSheetName', models.CharField(default=None, max_length=40)),
                ('itemBeingMeasured', models.CharField(default=None, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TestSequenceExternal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testName', models.CharField(default=None, max_length=40)),
                ('enableTest', models.BooleanField(default=True)),
                ('waterVolInML', models.FloatField(default=5.0)),
                ('reagent1Slot', models.CharField(default='A', max_length=1)),
                ('reagent1AgitateSecs', models.IntegerField(default=0)),
                ('reagent1DropCount', models.IntegerField(default=0)),
                ('reagent2Slot', models.CharField(default='A', max_length=1)),
                ('reagent2AgitateSecs', models.IntegerField(default=0)),
                ('reagent2DropCount', models.IntegerField(default=0)),
                ('reagent3Slot', models.CharField(default='A', max_length=1)),
                ('reagent3AgitateSecs', models.IntegerField(default=0)),
                ('reagent3DropCount', models.IntegerField(default=0)),
                ('agitateMixtureSecs', models.IntegerField(default=0)),
                ('delayBeforeReadingSecs', models.IntegerField(default=0)),
                ('tooLowAlarmThreshold', models.FloatField(default=None)),
                ('tooLowWarningThreshold', models.FloatField(default=None)),
                ('tooHighWarningThreshold', models.FloatField(default=None)),
                ('tooHighAlarmThreshold', models.FloatField(default=None)),
                ('selectByDayOfWeek', models.BooleanField(default=False)),
                ('dayOfWeek', models.CharField(choices=[('SUN', 'Sunday'), ('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday')], default='MON', max_length=3)),
                ('dayInterval', models.IntegerField(default=1)),
                ('hoursToRun', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23')], default='12', max_length=1)),
                ('colorChartToUse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tester.ColorSheetExternal')),
            ],
        ),
        migrations.RenameField(
            model_name='testresultsexternal',
            old_name='testResults',
            new_name='results',
        ),
    ]
