# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 23:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0006_testerfeatureexternal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testerfeatureexternal',
            old_name='usesRow',
            new_name='usesRaw',
        ),
    ]
