# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 00:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0007_auto_20170904_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='LightingConditionsExternal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lightingConditionName', models.CharField(default='LED', max_length=40)),
                ('channel1', models.FloatField(default=0)),
                ('channel2', models.FloatField(default=0)),
                ('channel3', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SwatchExternal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('swatchRow', models.IntegerField(default=1)),
                ('valueAtSwatch', models.FloatField(default=0)),
                ('channel1', models.FloatField(default=0)),
                ('channel2', models.FloatField(default=0)),
                ('channel3', models.FloatField(default=0)),
                ('swatchULRow', models.IntegerField(default=-20)),
                ('swatchULCol', models.IntegerField(default=-20)),
                ('swatchLRRow', models.IntegerField(default=20)),
                ('swatchLRCol', models.IntegerField(default=20)),
                ('colorSheetName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tester.ColorSheetExternal')),
                ('lightingConditions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tester.LightingConditionsExternal')),
            ],
        ),
    ]
