# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0008_lightingconditionsexternal_swatchexternal'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorsheetexternal',
            name='maxPermissableValue',
            field=models.FloatField(default=1000),
        ),
        migrations.AddField(
            model_name='colorsheetexternal',
            name='minPermissableValue',
            field=models.FloatField(default=0),
        ),
    ]
