# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0009_auto_20170904_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsequenceexternal',
            name='tooHighAlarmThreshold',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='testsequenceexternal',
            name='tooHighWarningThreshold',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='testsequenceexternal',
            name='tooLowAlarmThreshold',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='testsequenceexternal',
            name='tooLowWarningThreshold',
            field=models.FloatField(default=None, null=True),
        ),
    ]
