# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 02:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0012_auto_20170904_2150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testresultsexternal',
            old_name='datePerformed',
            new_name='datetimePerformed',
        ),
    ]
