# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 04:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0013_auto_20170904_2152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='swatchexternal',
            old_name='colorSheetName',
            new_name='sheetName',
        ),
    ]
