# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 04:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0014_auto_20170904_2327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='swatchexternal',
            old_name='sheetName',
            new_name='colorSheetName',
        ),
    ]
