# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0015_auto_20170904_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresultsexternal',
            name='datetimePerformed',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
