# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0016_auto_20170905_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselSlotExternal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slotName', models.CharField(default='A', max_length=1)),
                ('reagentName', models.CharField(default=None, max_length=40, null=True)),
                ('used', models.BooleanField(default=False)),
                ('hasAgitator', models.BooleanField(default=False)),
                ('fluidRemainingInML', models.FloatField(default=0)),
                ('reagentType', models.CharField(choices=[('Liquid', 'Liquid'), ('Powder', 'Powder')], default='Liquid', max_length=6)),
                ('color', models.CharField(default=None, max_length=40, null=True)),
                ('reagentInserted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
