# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 20:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0017_carouselslotexternal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carouselslotexternal',
            options={'ordering': ['slotName']},
        ),
    ]
