# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 22:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0018_auto_20170905_1532'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colorsheetexternal',
            options={'ordering': ['colorSheetName']},
        ),
        migrations.AlterModelOptions(
            name='lightingconditionsexternal',
            options={'ordering': ['lightingConditionName']},
        ),
        migrations.AlterModelOptions(
            name='swatchexternal',
            options={'ordering': ['colorSheetName__colorSheetName', 'lightingConditions', 'swatchRow']},
        ),
        migrations.AlterModelOptions(
            name='testerfeatureexternal',
            options={'ordering': ['featureName']},
        ),
        migrations.AlterModelOptions(
            name='testresultsexternal',
            options={'ordering': ['datetimePerformed']},
        ),
        migrations.AlterModelOptions(
            name='testsequenceexternal',
            options={'ordering': ['testName']},
        ),
    ]
