# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 22:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0019_auto_20170905_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsequenceexternal',
            name='reagent1Slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reagent1', to='tester.CarouselSlotExternal'),
        ),
        migrations.AlterField(
            model_name='testsequenceexternal',
            name='reagent2Slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reagent2', to='tester.CarouselSlotExternal'),
        ),
        migrations.AlterField(
            model_name='testsequenceexternal',
            name='reagent3Slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reagent3', to='tester.CarouselSlotExternal'),
        ),
    ]
