# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0020_auto_20170905_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='testerprocessingparameters',
            name='skipOrientation',
            field=models.BooleanField(default=False),
        ),
    ]
