# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0021_testerprocessingparameters_skiporientation'),
    ]

    operations = [
        migrations.AddField(
            model_name='testerexternal',
            name='webPort',
            field=models.IntegerField(default=8000),
        ),
    ]
