# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0022_testerexternal_webport'),
    ]

    operations = [
        migrations.AddField(
            model_name='testerfeatureexternal',
            name='confidenceThreshold',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='testerfeatureexternal',
            name='showConfidenceValues',
            field=models.BooleanField(default=False),
        ),
    ]
