# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 01:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0024_auto_20170906_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobName', models.CharField(max_length=40)),
                ('jobText', models.CharField(max_length=40)),
                ('jobAction', models.CharField(max_length=40)),
                ('timeStamp', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'ordering': ['timeStamp'],
            },
        ),
    ]
