# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0026_jobentry_jobindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='testsequenceexternal',
            name='hoursToRun',
        ),
        migrations.AddField(
            model_name='testsequenceexternal',
            name='hoursToRun',
            field=models.ManyToManyField(null=True, to='tester.HourChoices'),
        ),
    ]
