# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0028_auto_20170907_1153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hourchoices',
            options={'ordering': ['hour']},
        ),
        migrations.AlterField(
            model_name='hourchoices',
            name='hour',
            field=models.TimeField(default=0),
        ),
    ]
