# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 17:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0033_auto_20170907_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testsequenceexternal',
            name='dayInterval',
        ),
        migrations.RemoveField(
            model_name='testsequenceexternal',
            name='selectByDayOfWeek',
        ),
    ]
