# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 17:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0034_auto_20170907_1224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testsequenceexternal',
            old_name='dayOfWeek',
            new_name='daysToRun',
        ),
    ]
