# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 22:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0036_auto_20170907_1635'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarouselSlotExternal',
            new_name='ReagentSetup',
        ),
    ]
