# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 19:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0039_jobexternal_jobcause'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobexternal',
            old_name='JobCause',
            new_name='jobCause',
        ),
    ]
