# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0040_auto_20170908_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresultsexternal',
            name='status',
            field=models.CharField(default='Completed', max_length=200),
        ),
    ]
