# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 22:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0043_auto_20170908_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reagentsetup',
            name='color',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='reagentsetup',
            name='reagentInserted',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='testdefinition',
            name='tooHighAlarmThreshold',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='testdefinition',
            name='tooHighWarningThreshold',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='testdefinition',
            name='tooLowAlarmThreshold',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='testdefinition',
            name='tooLowWarningThreshold',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
