# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 02:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0046_auto_20170908_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testerexternal',
            old_name='fillTimeForPerML',
            new_name='fillTimePerML',
        ),
    ]
