# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 08:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0047_auto_20170909_0236'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enableSchedule', models.BooleanField(default=True)),
                ('daysToRun', models.CharField(choices=[('Everyday', 'Everyday'), ('2day', 'Every 2 days'), ('3day', 'Every 3 days'), ('4day', 'Every 4 days'), ('5day', 'Every 5 days'), ('10day', 'Every 10 days'), ('Sunday', 'Every Sunday'), ('Monday', 'Every Monday'), ('Tuesday', 'Every Tuesday'), ('Wednesday', 'Every Wednesday'), ('Thursday', 'Every Thursday'), ('Friday', 'Every Friday'), ('Saturday', 'Every Saturday'), ('14day', 'Every 2 weeks'), ('21day', 'Every 3 weeks'), ('28day', 'Every 4 weeks'), ('Never', 'Never')], default='Never', max_length=10, null=True)),
                ('hoursToRun', models.ManyToManyField(blank=True, to='tester.HourChoices')),
            ],
            options={
                'ordering': ['testToSchedule__testName'],
            },
        ),
        migrations.RemoveField(
            model_name='testdefinition',
            name='daysToRun',
        ),
        migrations.RemoveField(
            model_name='testdefinition',
            name='hoursToRun',
        ),
        migrations.AddField(
            model_name='testschedule',
            name='testToSchedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tester.TestDefinition'),
        ),
    ]
