# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 13:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0048_auto_20170912_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorsheetexternal',
            name='colorSheetName',
            field=models.CharField(default=None, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='hourchoices',
            name='hour',
            field=models.TimeField(unique=True),
        ),
        migrations.AlterField(
            model_name='lightingconditionsexternal',
            name='lightingConditionName',
            field=models.CharField(default='LED', max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='reagentsetup',
            name='slotName',
            field=models.CharField(default='A', max_length=1, unique=True),
        ),
        migrations.AlterField(
            model_name='testdefinition',
            name='testName',
            field=models.CharField(default=None, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='testerfeatureexternal',
            name='featureName',
            field=models.CharField(default='dummy Feature', max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='testschedule',
            name='testToSchedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tester.TestDefinition', unique=True),
        ),
    ]
