# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0049_auto_20170912_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testschedule',
            name='testToSchedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tester.TestDefinition'),
        ),
    ]
