# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0051_auto_20170912_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testschedule',
            name='testToSchedule',
            field=models.CharField(default='Dummy', max_length=40, null=True),
        ),
    ]
