# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-17 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0057_auto_20170916_0407'),
    ]

    operations = [
        migrations.AddField(
            model_name='testerfeatureexternal',
            name='userTrainable',
            field=models.BooleanField(default=False),
        ),
    ]
