# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-17 01:28
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0058_testerfeatureexternal_usertrainable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorsheetexternal',
            name='colorSheetName',
            field=models.CharField(default=None, help_text='Name of the colorsheet.  A recommended format is whatIsBeingTested-manufacturer', max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='colorsheetexternal',
            name='itemBeingMeasured',
            field=models.CharField(default=None, help_text='What the test measures', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='colorsheetexternal',
            name='maxPermissableValue',
            field=models.FloatField(default=1000, help_text='Maximum possible reading from the test'),
        ),
        migrations.AlterField(
            model_name='colorsheetexternal',
            name='minPermissableValue',
            field=models.FloatField(default=0, help_text='Minimum possible reading from the test'),
        ),
        migrations.AlterField(
            model_name='hourchoices',
            name='hour',
            field=models.TimeField(help_text='Tests are on hour boundaries', unique=True),
        ),
        migrations.AlterField(
            model_name='reagentsetup',
            name='color',
            field=models.CharField(blank=True, default=None, help_text='An optional description of the color of the reagent', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='reagentsetup',
            name='fluidRemainingInML',
            field=models.FloatField(default=0, help_text='The amount of usable reagent remaining (computed by the machine)'),
        ),
        migrations.AlterField(
            model_name='reagentsetup',
            name='hasAgitator',
            field=models.BooleanField(default=False, help_text='Is there an agitator magnet in the syringe'),
        ),
        migrations.AlterField(
            model_name='reagentsetup',
            name='reagentInserted',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, help_text='When was the reagent last replaced', null=True),
        ),
        migrations.AlterField(
            model_name='reagentsetup',
            name='reagentName',
            field=models.CharField(default=None, help_text='A descriptive name of the reagent', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='reagentsetup',
            name='reagentType',
            field=models.CharField(choices=[('Liquid', 'Liquid'), ('Powder', 'Powder')], default='Liquid', help_text='The type of reagent', max_length=6),
        ),
        migrations.AlterField(
            model_name='reagentsetup',
            name='slotName',
            field=models.CharField(default='A', help_text='The carousel slot letter', max_length=1, unique=True),
        ),
        migrations.AlterField(
            model_name='reagentsetup',
            name='used',
            field=models.BooleanField(default=False, help_text='Is there anything in the slot (an empty syringe is No)'),
        ),
        migrations.AlterField(
            model_name='testdefinition',
            name='reagent1DropCount',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='testerexternal',
            name='testerName',
            field=models.CharField(default='AutoTester', help_text='Name of the model', max_length=200),
        ),
        migrations.AlterField(
            model_name='testresultsexternal',
            name='datetimePerformed',
            field=models.DateTimeField(auto_now_add=True, help_text='When the test was run'),
        ),
        migrations.AlterField(
            model_name='testresultsexternal',
            name='results',
            field=models.FloatField(blank=True, default=None, help_text='Numeric results from running the test', null=True),
        ),
        migrations.AlterField(
            model_name='testresultsexternal',
            name='status',
            field=models.CharField(default='Completed', help_text='Completion status of the test', max_length=200),
        ),
        migrations.AlterField(
            model_name='testresultsexternal',
            name='testPerformed',
            field=models.CharField(default=None, help_text='This was the test that was run', max_length=200),
        ),
    ]
