# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-17 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0059_auto_20170917_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='testerfeatureexternal',
            name='modelRequired',
            field=models.BooleanField(default=True),
        ),
    ]
