# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-17 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0060_testerfeatureexternal_modelrequired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testerexternal',
            name='iftttSecretKey',
            field=models.CharField(default=None, help_text='How to set up webhooks and get secret key: https://www.hackster.io/ali-ozkil/ifttt-maker-channel-triggers-21365b', max_length=50),
        ),
        migrations.AlterField(
            model_name='testerexternal',
            name='testerName',
            field=models.CharField(default='AutoTester', max_length=200),
        ),
    ]
