# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0062_testerexternal_currenttimezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='testerexternal',
            name='dbModelVersion',
            field=models.CharField(default='v1.0', max_length=40),
        ),
    ]
