# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0063_testerexternal_dbmodelversion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testdefinition',
            old_name='reagent1DropCount',
            new_name='reagent1DispenseCount',
        ),
        migrations.RenameField(
            model_name='testdefinition',
            old_name='reagent2DropCount',
            new_name='reagent2DispenseCount',
        ),
        migrations.RenameField(
            model_name='testdefinition',
            old_name='reagent3DropCount',
            new_name='reagent3DispenseCount',
        ),
        migrations.AddField(
            model_name='testdefinition',
            name='reagent1DispenseType',
            field=models.CharField(choices=[('Drops', 'Drops'), ('ml', 'ml')], default='Drops', help_text='How to measure dispensing', max_length=6),
        ),
        migrations.AddField(
            model_name='testdefinition',
            name='reagent2DispenseType',
            field=models.CharField(choices=[('Drops', 'Drops'), ('ml', 'ml')], default='Drops', help_text='How to measure dispensing', max_length=6),
        ),
        migrations.AddField(
            model_name='testdefinition',
            name='reagent3DispenseType',
            field=models.CharField(choices=[('Drops', 'Drops'), ('ml', 'ml')], default='Drops', help_text='How to measure dispensing', max_length=6),
        ),
    ]
