# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 14:44
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0064_auto_20170920_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdefinition',
            name='reagent1DispenseCount',
            field=models.FloatField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0.05), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='testdefinition',
            name='reagent1DispenseType',
            field=models.CharField(choices=[('drops', 'drops'), ('ml', 'ml')], default='drops', help_text='How to measure dispensing', max_length=6),
        ),
        migrations.AlterField(
            model_name='testdefinition',
            name='reagent2DispenseType',
            field=models.CharField(choices=[('drops', 'drops'), ('ml', 'ml')], default='Drops', help_text='How to measure dispensing', max_length=6),
        ),
        migrations.AlterField(
            model_name='testdefinition',
            name='reagent3DispenseType',
            field=models.CharField(choices=[('drops', 'drops'), ('ml', 'ml')], default='Drops', help_text='How to measure dispensing', max_length=6),
        ),
    ]
