# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0065_auto_20170920_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='testerexternal',
            name='virtualEnvironmentName',
            field=models.CharField(default='cv', max_length=40),
        ),
    ]
