# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0066_testerexternal_virtualenvironmentname'),
    ]

    operations = [
        migrations.AddField(
            model_name='testerprocessingparameters',
            name='maxImageRotationWithoutAdjustment',
            field=models.FloatField(default=2),
        ),
        migrations.AddField(
            model_name='testerprocessingparameters',
            name='maxImageScalingWithoutAdjustment',
            field=models.FloatField(default=1.05),
        ),
        migrations.AddField(
            model_name='testerprocessingparameters',
            name='minImageRotationWithoutAdjustment',
            field=models.FloatField(default=-2),
        ),
        migrations.AddField(
            model_name='testerprocessingparameters',
            name='minImageScalingWithoutAdjustment',
            field=models.FloatField(default=0.95),
        ),
    ]
