# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0067_auto_20170921_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='testerprocessingparameters',
            name='defaultFisheyeExpansionFactor',
            field=models.FloatField(default=1.2),
        ),
    ]
