# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0069_auto_20170922_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='TesterStartupInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seatedGap', models.FloatField(default=2)),
                ('unseatedGap', models.FloatField(default=0)),
            ],
        ),
    ]
