# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0070_testerstartupinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='testerexternal',
            name='manageDatabases',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testerprocessingparameters',
            name='gapTolerance',
            field=models.FloatField(default=5.0),
        ),
    ]
