# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 23:07
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0071_auto_20170922_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testerexternal',
            name='videoStreamingPort',
            field=models.IntegerField(default=8080, validators=[django.core.validators.MinValueValidator(1001), django.core.validators.MaxValueValidator(65535)]),
        ),
        migrations.AlterField(
            model_name='testerexternal',
            name='webPort',
            field=models.IntegerField(default=8000, validators=[django.core.validators.MinValueValidator(1001), django.core.validators.MaxValueValidator(65535)]),
        ),
    ]
