# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-23 23:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0073_auto_20170923_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='testerexternal',
            name='mlDisplacedByMagnet',
            field=models.FloatField(default=0.34, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
