# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 00:50
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0074_testerexternal_mldisplacedbymagnet'),
    ]

    operations = [
        migrations.AddField(
            model_name='testerexternal',
            name='mixerWaterLevelAdjustment',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(-2), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AlterField(
            model_name='testerexternal',
            name='iftttSecretKey',
            field=models.CharField(blank=True, default=None, help_text='How to set up webhooks and get secret key: https://www.hackster.io/ali-ozkil/ifttt-maker-channel-triggers-21365b', max_length=50),
        ),
    ]
