# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 20:28
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0075_auto_20170924_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='testerexternal',
            name='maxPlungerDepthAgitator',
            field=models.FloatField(default=58, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='testerexternal',
            name='maxPlungerDepthNoAgitator',
            field=models.FloatField(default=70, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
