# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-05 23:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0077_resultsswatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultsswatch',
            name='lightingConditions',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tester.LightingConditionsExternal'),
        ),
        migrations.AlterField(
            model_name='resultsswatch',
            name='results',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='swatchForResults', to='tester.TestResultsExternal'),
        ),
        migrations.AlterField(
            model_name='resultsswatch',
            name='swatchDropCount',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
