# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-06 13:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0078_auto_20171005_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultsswatch',
            name='lightingConditions',
        ),
        migrations.RemoveField(
            model_name='resultsswatch',
            name='results',
        ),
        migrations.AlterField(
            model_name='testresultsexternal',
            name='datetimePerformed',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='When the test was run'),
        ),
        migrations.DeleteModel(
            name='ResultsSwatch',
        ),
    ]
