# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-07 16:26
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0080_testresultsexternal_swatchfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdefinition',
            name='titrationAgitateSecs',
            field=models.IntegerField(default=1, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AddField(
            model_name='testdefinition',
            name='titrationDispenseType',
            field=models.CharField(choices=[('drops', 'drops'), ('ml', 'ml')], default='drops', help_text='How to measure dispensing', max_length=6),
        ),
        migrations.AddField(
            model_name='testdefinition',
            name='titrationMaxDispenses',
            field=models.FloatField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0.05), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AddField(
            model_name='testdefinition',
            name='titrationSlot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='titration', to='tester.ReagentSetup'),
        ),
        migrations.AddField(
            model_name='testdefinition',
            name='titrationTransition',
            field=models.FloatField(default=0.5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
