# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-07 14:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0082_auto_20171007_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testerexternal',
            name='currentTimeZone',
        ),
        migrations.AddField(
            model_name='testerexternal',
            name='daysOfResultsToKeep',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='testdefinition',
            name='reagent1Slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reagent1', to='tester.ReagentSetup'),
        ),
    ]
