# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-07 23:58
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0083_auto_20171007_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdefinition',
            name='reagent1DispenseCount',
            field=models.FloatField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)]),
        ),
    ]
